### PR TITLE
Use of JAVA_OPTS instead of CATALINA_OPTS. Fix for #602

### PR DESCRIPTION
**Pull request by vjrj**
Following https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=956804 fix for task of #598 and #602.

### CODE REVIEW

**Comment by sbearcsiro** [comment]
The Debian maintainer seems to not understand `CATALINA_OPTS`.  `CATALINA_OPTS` is correct AFAIK.

`CATALINA_OPTS` is used only for `catalina.sh` `run`, `start` and `debug`, so you're not setting, eg `Xmx=4G` and `Xms=4G` when running `catalina.sh stop` (which launches a separate jvm process with `JAVA_OPTS` that stops tomcat.  Or at least it did back in the day).

The above still holds for Tomcat 9, I've just checked the package locally.

**Comment by sbearcsiro** [comment]
Seems like we could uselineinfile: {

**Comment by vjrj** [comment]
Thanks @sbearcsiro for the clarifications. Anyway, if you check `ala-install` we only use `CATALINA_OPTS` to set the `GEOSERVER_DATA_DIR` and `GEOWEBCACHE_CACHE_DIR`. So I think that don't merit the effort (to send patch to debian) if we can accomplish the same using `JAVA_OPTS` in the geoserver install.

**Comment by sbearcsiro** [comment]
Thanks @vjrj, you're right, it's not setting memory limits or anything so this change is fine IMHO.

**Pull request merged**
